import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";

type Banner = { image: string; title: string; subtitle: string; light?: boolean };
const banners: Banner[] = [
  { image: "https://www.figma.com/api/mcp/asset/2b7a5f5f-d1f7-4d18-9dd5-dfd1df1a3f24.png", title: "대한민국 퍼스트 브랜드\n유학기업 부문 대상 수상", subtitle: "15년 연속, 유학기업 1위!", light: true },
  { image: "https://www.figma.com/api/mcp/asset/779f81e0-2b49-4c99-92f3-2b6b43b65eff.png", title: "유튜브, 블로그\n후기를 확인하세요!", subtitle: "실제 유학 생활 살펴보기" },
  { image: "https://www.figma.com/api/mcp/asset/b6df0645-26ee-496e-b84f-d607d668ff38.png", title: "특별한 유학 생활\n다양한 커뮤니티", subtitle: "edm유학센터 수속 고객 단독 제공" },
  { image: "https://www.figma.com/api/mcp/asset/8697b1a3-b315-477d-a2f6-f9f2110ce67d.png", title: "업계 최고 수준의\n특별한 혜택", subtitle: "edm유학센터 수속 고객 단독 제공" },
  { image: "https://www.figma.com/api/mcp/asset/c2e21ceb-2e28-4b58-a174-ca082b35315c.png", title: "안전 유학 원칙\n고객을 위한 진심", subtitle: "검증된 학교 추천, 투명한 절차", light: true },
];

const cls = (...values: Array<string | false | undefined>) => values.filter(Boolean).join(" ");

function Logo() { return <a href="#top" className="flex items-baseline gap-1.5 text-[#333]"><strong className="text-[25px] font-black tracking-[-.13em] text-[#444]">ed<span className="text-[#54b948]">:</span>m</strong><span className="text-[12px] font-bold">유학센터</span></a>; }

function Header() { return <header className="flex h-[60px] items-center justify-between border-b border-[#eee] bg-white px-5 lg:h-[64px] lg:px-[54px]"><Logo /><nav className="hidden items-center gap-8 text-[11px] font-medium lg:flex"><a href="#program">어학연수</a><a href="#program">해외대학</a><a href="#program">조기유학/캠프</a><a href="#guide">아트유학</a><a href="#guide">유학후기</a><a href="#guide">고객백화</a><a href="#guide">회사소개</a></nav><div className="flex items-center gap-4"><button className="hidden rounded-full bg-[#f1f1f3] px-4 py-2 text-[10px] lg:block">⌕　프로그램 | 학교</button><button aria-label="로그인" className="text-lg">♙</button><button aria-label="로그아웃" className="text-lg">↪</button><button aria-label="메뉴" className="text-lg">☰</button></div></header>; }

function BannerCard({ banner }: { banner: Banner }) { return <article className={cls("relative h-[195px] min-w-[calc(100vw-40px)] overflow-hidden rounded-[12px] bg-cover bg-center p-5 shadow-sm sm:min-w-[310px] lg:h-[195px] lg:min-w-0 lg:flex-1 lg:p-5", banner.light ? "text-white" : "text-black")} style={{ backgroundImage: `url(${banner.image})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/5 via-transparent to-black/10" /><div className="relative"><h2 className="whitespace-pre-line text-[20px] font-extrabold leading-[1.2] tracking-[-.06em] lg:text-[19px]">{banner.title}</h2><p className="mt-2 text-[10px]">{banner.subtitle}</p></div><span className="absolute bottom-4 left-5 rounded-full bg-black/85 px-2.5 py-1 text-[9px] font-bold text-white">25.10.10~15</span></article>; }

function SearchPanel() { const [tab, setTab] = useState("프로그램"); return <section className="relative z-10 bg-white px-5 pb-[70px] pt-[36px] lg:px-[54px] lg:pb-[70px] lg:pt-[36px]"><div className="mx-auto flex max-w-[850px] flex-col gap-8 lg:flex-row lg:items-center lg:gap-16"><div className="shrink-0"><h2 className="text-[21px] font-extrabold tracking-[-.07em] lg:text-[20px]">유학 프로그램 빠른 검색</h2><p className="mt-2 text-[11px] leading-[1.55] text-[#555]">전세계 <b className="text-[#ee3943]">1,474</b>개 학교와 <b className="text-[#ee3943]">71</b>개 프로그램 제공<br />국가별 맞춤 필터로 효율적으로 탐색하세요.</p></div><div className="w-full rounded-[13px] border border-[#e4e4e4] bg-white px-5 py-4 shadow-[0_5px_14px_rgba(0,0,0,.12)] lg:flex-1"><div className="mb-4 flex gap-6 text-[10px]"><button onClick={() => setTab("프로그램")} className={tab === "프로그램" ? "border-b-2 border-[#20c65a] pb-1 font-bold text-[#20c65a]" : "text-[#999]"}>프로그램</button><button onClick={() => setTab("학교/기관")} className={tab === "학교/기관" ? "border-b-2 border-[#20c65a] pb-1 font-bold text-[#20c65a]" : "text-[#999]"}>학교/기관</button></div><div className="grid grid-cols-[1fr_1fr_70px] gap-3"><button className="flex h-[38px] items-center justify-between rounded-[4px] bg-[#f5f5f7] px-3 text-left text-[9px] text-[#777]">유형 <b className="block text-[10px] text-black">유형전체(5)</b><span>⌄</span></button><button className="flex h-[38px] items-center justify-between rounded-[4px] bg-[#f5f5f7] px-3 text-left text-[9px] text-[#777]">국가 <b className="block text-[10px] text-black">국가전체(8)</b><span>⌄</span></button><button className="h-[38px] rounded-[4px] bg-[#1bc956] text-[11px] font-bold text-white">검색</button></div></div></div></section>; }

function App() { const [slide, setSlide] = useState(0); return <div id="top" className="min-h-screen bg-white text-[#111]"><Header /><main><section id="program" className="overflow-hidden px-5 pb-0 pt-6 lg:px-[54px] lg:pt-5"><div className="mx-auto max-w-[850px]"><div className="mb-4 flex items-center justify-between"><h1 className="text-[11px] font-bold text-[#555]">edm 유학센터</h1><span className="text-[10px] text-[#999]">다양한 프로그램을 만나보세요</span></div><div className="flex gap-2.5 overflow-hidden lg:gap-2.5">{banners.map((banner, index) => <div key={banner.title} className={cls("w-full lg:flex", index < slide && "hidden lg:flex")}><BannerCard banner={banner} /></div>)}</div><div className="mt-4 flex items-center justify-end gap-2 text-[10px]"><b>{String(slide + 1).padStart(2, "0")}</b><span className="text-[#999]">/12</span><button onClick={() => setSlide((value) => Math.max(0, value - 1))} className="grid h-6 w-6 place-items-center rounded-full bg-[#ededee]" aria-label="이전 배너">‹</button><button onClick={() => setSlide((value) => Math.min(banners.length - 1, value + 1))} className="grid h-6 w-6 place-items-center rounded-full bg-[#ededee]" aria-label="다음 배너">›</button></div></div></section><SearchPanel /><section className="h-[88px] overflow-hidden bg-gradient-to-r from-[#eef0ff] via-[#e6e8ff] to-[#d8eaff] lg:h-[110px]"><div className="mx-auto max-w-[850px] pt-8"><div className="h-20 w-20 -rotate-12 rounded-[50%] border-[5px] border-[#7e86ff] bg-[#99b8ff] opacity-70 shadow-[8px_-6px_0_#a9b1ff,16px_-12px_0_#c1b5ff]" /></div></section></main><aside className="fixed right-0 top-[154px] z-20 hidden w-[49px] overflow-hidden rounded-l-[10px] border border-[#e6e6e6] bg-white shadow-md lg:block"><a href="#program" className="flex h-[47px] flex-col items-center justify-center gap-1 border-b text-[8px]">♙<span>상담예약</span></a><a href="#guide" className="flex h-[47px] flex-col items-center justify-center gap-1 border-b text-[8px]">☏<span>채팅상담</span></a><a href="#guide" className="flex h-[47px] flex-col items-center justify-center gap-1 border-b text-[8px]">▱<span>자료집</span></a><div className="bg-[#19c85b] py-2 text-center text-[8px] font-bold text-white">Develop</div><a href="#guide" className="flex h-[47px] flex-col items-center justify-center gap-1 text-[8px]">▣<span>가이드북</span></a></aside><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="맨 위로" className="fixed bottom-4 right-4 z-20 grid h-8 w-8 place-items-center rounded-full border border-[#ddd] bg-white text-lg shadow-sm">↑</button><footer id="guide" className="sr-only">edm 유학센터</footer></div>; }

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
