import { StrictMode, useEffect, useState } from "react";
import { createRoot, type Root } from "react-dom/client";
import "./index.css";

type Banner = { image: string; title: string; subtitle: string; light?: boolean };
const banners: Banner[] = [
  { image: "https://www.figma.com/api/mcp/asset/2b7a5f5f-d1f7-4d18-9dd5-dfd1df1a3f24.png", title: "유학기업 1위\n16년 연속 수상", subtitle: "2026 퍼스트 브랜드 대상", light: true },
  { image: "https://www.figma.com/api/mcp/asset/779f81e0-2b49-4c99-92f3-2b6b43b65eff.png", title: "AI로 다 찾아봤는데\n상담이 필요할까요?", subtitle: "유학 컨설턴트 현장 설문 리포트" },
  { image: "https://www.figma.com/api/mcp/asset/b6df0645-26ee-496e-b84f-d607d668ff38.png", title: "국내 1위\n수속 고객 혜택", subtitle: "edm이기에 가능한 압도적 서비스" },
  { image: "https://www.figma.com/api/mcp/asset/8697b1a3-b315-477d-a2f6-f9f2110ce67d.png", title: "+9,999 압도적 후기\n이유가 있습니다!", subtitle: "고객의 꿈, 우리의 미션" },
  { image: "https://www.figma.com/api/mcp/asset/c2e21ceb-2e28-4b58-a174-ca082b35315c.png", title: "고객을 향한 진심\n안전 유학", subtitle: "환불, 검증된 학교 추천, 학비 송금, 투명한 절차", light: true },
  { image: "https://www.figma.com/api/mcp/asset/b1a90317-3f04-4631-aebd-ebc93c36da9a.png", title: "현대 면세점\n제휴 혜택", subtitle: "edm 수속 고객, 인천공항점 할인" },
  { image: "https://www.figma.com/api/mcp/asset/f33c5700-229b-4598-97d4-4ada1f42e2a8.png", title: "특별한 유학 생활\nedm 커뮤니티", subtitle: "edm유학센터 수속 고객 단독 제공" },
  { image: "https://www.figma.com/api/mcp/asset/0c8dcb49-383c-45d5-b448-0c3570e060f2.png", title: "빠르고 정확한 견적\nedm QPro 출시", subtitle: "국내유일, 어학연수 자동 견적 시스템", light: true },
];

const cls = (...values: Array<string | false | undefined>) => values.filter(Boolean).join(" ");
function Icon({ name, size = 20 }: { name: "search" | "user" | "menu" | "logout"; size?: number }) {
  const paths = { search: <><circle cx="10.5" cy="10.5" r="6.5" /><path d="m16 16 5 5" /></>, user: <><circle cx="12" cy="8" r="4" /><path d="M4 21c.8-4 3.5-6 8-6s7.2 2 8 6" /></>, logout: <><path d="M13 5h7v14h-7" /><path d="M3 12h11m-4-4 4 4-4 4" /></>, menu: <><path d="M3 6h18M3 12h18M3 18h18" /></> }[name];
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths}</svg>;
}

function Logo() { return <a href="#top" aria-label="edm 유학센터 홈" className="block"><img src="/edm-logo.svg" alt="edm 유학센터" className="h-[22px] w-auto md:h-[35px]" /></a>; }

function Header() { return <header className="relative z-[var(--z-header)] flex h-[60px] items-center justify-between border-b border-[#eee] bg-white px-5 md:h-[64px] md:px-[120px]"><Logo /><nav className="hidden items-center gap-10 text-[11px] font-medium md:flex"><a href="#program">어학연수</a><a href="#program">해외대학</a><a href="#program">조기유학/캠프</a><a href="#guide">아트유학</a><a href="#guide">유학후기</a><a href="#guide">고객혜택</a><a href="#guide">회사소개</a></nav><div className="flex items-center gap-5"><button className="hidden items-center gap-3 rounded-full bg-[#E2E2E5] px-4 py-2 text-[10px] md:flex"><Icon name="search" size={15} />프로그램 <span className="h-3 border-l border-[#333]" /> 학교</button><button aria-label="로그인" className="text-[#333]"><Icon name="user" size={20} /></button><button aria-label="로그아웃" className="text-[#333]"><Icon name="logout" size={20} /></button><button aria-label="메뉴" className="text-[#333]"><Icon name="menu" size={20} /></button></div></header>; }

function BannerCard({ banner }: { banner: Banner }) { return <article className={cls("relative h-[195px] min-w-[calc(100vw-40px)] overflow-hidden rounded-[12px] bg-cover bg-center p-5 shadow-sm sm:min-w-[310px] md:h-[390px] md:min-w-[480px] md:flex-none md:rounded-[24px] md:p-10", banner.light ? "text-white" : "text-black")} style={{ backgroundImage: `url(${banner.image})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/5 via-transparent to-black/10" /><div className="relative"><h2 className="whitespace-pre-line text-[20px] font-extrabold leading-[1.2] tracking-[-.06em] md:text-[19px]">{banner.title}</h2><p className="mt-2 text-[10px]">{banner.subtitle}</p></div><span className="absolute bottom-4 left-5 rounded-full bg-black/85 px-2.5 py-1 text-[9px] font-bold text-white">25.10.10~15</span></article>; }

function SearchPanel() { const [tab, setTab] = useState("프로그램"); return <section className="relative z-10 bg-white px-5 pb-[70px] pt-[36px] md:px-[120px] md:pb-[116px] md:pt-0"><div className="mx-auto flex max-w-[1680px] flex-col gap-8 md:flex-row md:items-center md:gap-16"><div className="shrink-0"><h2 className="text-[21px] font-extrabold tracking-[-.07em] md:text-[20px]">유학 프로그램 빠른 검색</h2><p className="mt-2 text-[11px] leading-[1.55] text-[#555]">전세계 <b className="text-[#ee3943]">1,474</b>개 학교와 <b className="text-[#ee3943]">71</b>개 프로그램 제공<br />국가별 맞춤 필터로 효율적으로 탐색하세요.</p></div><div className="w-full rounded-[13px] border border-[#e4e4e4] bg-white px-5 py-4 shadow-[0_5px_14px_rgba(0,0,0,.12)] md:flex-1"><div className="mb-4 flex gap-6 text-[10px]"><button onClick={() => setTab("프로그램")} className={tab === "프로그램" ? "border-b-2 border-[#20c65a] pb-1 font-bold text-[#20c65a]" : "text-[#999]"}>프로그램</button><button onClick={() => setTab("학교/기관")} className={tab === "학교/기관" ? "border-b-2 border-[#20c65a] pb-1 font-bold text-[#20c65a]" : "text-[#999]"}>학교/기관</button></div><div className="grid grid-cols-[1fr_1fr_70px] gap-3"><button className="flex h-[38px] items-center justify-between rounded-[4px] bg-[#f5f5f7] px-3 text-left text-[9px] text-[#777]">유형 <b className="block text-[10px] text-black">유형전체(5)</b><span>⌄</span></button><button className="flex h-[38px] items-center justify-between rounded-[4px] bg-[#f5f5f7] px-3 text-left text-[9px] text-[#777]">국가 <b className="block text-[10px] text-black">국가전체(8)</b><span>⌄</span></button><button className="h-[38px] rounded-[4px] bg-[#1bc956] text-[11px] font-bold text-white">검색</button></div></div></div></section>; }

function App() { const [slide, setSlide] = useState(0); useEffect(() => { const timer = window.setInterval(() => setSlide((value) => (value + 1) % banners.length), 5000); return () => window.clearInterval(timer); }, []); return <div id="top" className="min-h-screen bg-white text-[#111]"><Header /><main><section id="program" className="overflow-hidden px-5 pb-0 pt-6 md:pb-[70px] md:px-[120px] md:pt-[60px]"><div className="mx-auto max-w-[1680px]"><div className="mb-4 flex items-center justify-between"><h1 className="text-[11px] font-bold text-[#555]">edm 유학센터</h1><span className="text-[10px] text-[#999]">다양한 프로그램을 만나보세요</span></div><div className="overflow-hidden"><div className="banner-track flex gap-2.5 md:gap-2.5" style={{ ["--banner-offset" as string]: `${slide * 496}px` }}>{banners.map((banner, index) => <div key={banner.title} className={cls("w-full md:w-[480px] md:flex-none", index < slide && "hidden md:flex")}><BannerCard banner={banner} /></div>)}</div></div><div className="mt-4 flex items-center justify-end gap-2 text-[10px]"><b>{String(slide + 1).padStart(2, "0")}</b><span className="text-[#999]">/8</span><button onClick={() => setSlide((value) => Math.max(0, value - 1))} className="grid h-6 w-6 place-items-center rounded-full bg-[#E2E2E5]" aria-label="이전 배너">‹</button><button onClick={() => setSlide((value) => Math.min(banners.length - 1, value + 1))} className="grid h-6 w-6 place-items-center rounded-full bg-[#E2E2E5]" aria-label="다음 배너">›</button></div></div></section><SearchPanel /><section className="h-[88px] overflow-hidden bg-gradient-to-r from-[#eef0ff] via-[#e6e8ff] to-[#d8eaff] md:h-[110px]"><div className="mx-auto max-w-[1680px] pt-8"><div className="h-20 w-20 -rotate-12 rounded-[50%] border-[5px] border-[#7e86ff] bg-[#99b8ff] opacity-70 shadow-[8px_-6px_0_#a9b1ff,16px_-12px_0_#c1b5ff]" /></div></section></main><aside className="fixed right-0 top-[154px] z-[var(--z-floating)] hidden w-[49px] overflow-hidden rounded-l-[10px] border border-[#e6e6e6] bg-white shadow-md md:block"><a href="#program" className="flex h-[47px] flex-col items-center justify-center gap-1 border-b text-[8px]"><Icon name="user" size={14} /><span>상담예약</span></a><a href="#guide" className="flex h-[47px] flex-col items-center justify-center gap-1 border-b text-[8px]">◌<span>채팅상담</span></a><a href="#guide" className="flex h-[47px] flex-col items-center justify-center gap-1 border-b text-[8px]">▱<span>자료집</span></a><div className="bg-[#1EC95B] py-2 text-center text-[8px] font-bold text-white">Develop</div><a href="#guide" className="flex h-[47px] flex-col items-center justify-center gap-1 text-[8px]">▣<span>가이드북</span></a></aside><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="맨 위로" className="fixed bottom-4 right-4 z-[var(--z-floating)] grid h-8 w-8 place-items-center rounded-full border border-[#ddd] bg-white text-lg shadow-sm">↑</button><footer id="guide" className="sr-only">edm 유학센터</footer></div>; }

const rootElement = document.getElementById("root")!;
if (import.meta.hot) {
  const hotData = import.meta.hot.data as { root?: Root };
  hotData.root ??= createRoot(rootElement);
  hotData.root.render(<StrictMode><App /></StrictMode>);
} else {
  createRoot(rootElement).render(<StrictMode><App /></StrictMode>);
}






